### ISSUE TITLE
Ability to cast strings to other types

### ISSUE THREAD

**Issue by moltar** [arvitaly/typio#1]
Not sure if this is in or outside the scope of the package, but as useful casting use case I have is casting `process.env` (which is always a string) to actual types.

E.g. literal string `true` to actual boolean type.

**Comment by arvitaly** [comment]
Hi, @moltar !
I don't see beautiful way to cast from any string to bool. The value "true" is very local sample of many variants, like "1" or "True" or any non-empty string. It can be dangerous.
But, typio supports any function as parameter, so, we can always write helper like this:

```typescript
function anyBool(): boolean {
    const castFn = (value: any) => typio(!!value, bool());
    return castFn as any;
}

const result = typio({ isHello: "any", isWorld: "" }, { isHello: anyBool(), isWorld: anyBool() });

console.log(typeof result.isHello, typeof result.isWorld); // boolean boolean
console.log(result.isHello === true); // true
console.log(result.isWorld === true); // false
```
Typescript type inference:
![image](https://user-images.githubusercontent.com/2562855/42486130-49bca948-8403-11e8-9f9b-276ee534e350.png)

**Comment by arvitaly** [comment]
For other types: int, date, float - casting from string already exists.

**Comment by moltar** [comment]
Ah, great! Thank you for the tips!

I built up on your answer and used `yn` module to detect the booleans:

```typescript
import { typio, bool } from 'typio'
import * as yn from 'yn'

function anyBool(): boolean {
  const castFn = (value: any) => typio(yn(value, { default: false }), bool());
  return castFn as any;
}

const result = typio({ isHello: "y", isWorld: 0 }, { isHello: anyBool(), isWorld: anyBool() });

console.log(result)
```
